version: '3.8'

services:
  # Service Registry (Eureka)
  eureka-server:
    image: springcloud/eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - stage-network

  # MySQL Database for Auth Service
  auth-db:
    image: mysql:8.0
    container_name: auth-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stage_auth_db
    ports:
      - "3307:3306"
    volumes:
      - auth_data:/var/lib/mysql
    networks:
      - stage-network

  # MySQL Database for User Service
  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stage_user_db
    ports:
      - "3308:3306"
    volumes:
      - user_data:/var/lib/mysql
    networks:
      - stage-network

  # MySQL Database for Internship Service
  internship-db:
    image: mysql:8.0
    container_name: internship-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stage_internship_db
    ports:
      - "3309:3306"
    volumes:
      - internship_data:/var/lib/mysql
    networks:
      - stage-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - stage-network

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - stage-network

  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - auth-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://auth-db:3306/stage_auth_db
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - stage-network

  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - user-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://user-db:3306/stage_user_db
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - stage-network

  # Internship Service
  internship-service:
    build: ./internship-service
    container_name: internship-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - internship-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://internship-db:3306/stage_internship_db
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - stage-network

  # Notification Service
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - redis
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_REDIS_HOST=redis
    networks:
      - stage-network

volumes:
  auth_data:
  user_data:
  internship_data:

networks:
  stage-network:
    driver: bridge